### ISSUE TITLE
代码不全

### ISSUE THREAD

**Issue by 373351708** [Spacewe-outlook/PPE#1]
你好，请问可以把您的全部代码发一下给我吗。 我导师最近让我研究您的算法并加以改进。谢谢！

**Comment by spcity** [comment]
你好，PPE012(1).zip文件中包含PPE算法、PSO算法和CEC13 14 17三个版本测试函数，可直接运行！谢谢。对比所需的其他算法设计到使用传播权的问题，你可从Matlab file exchange收集。
